# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-07 16:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.CharField(choices=[(0, 'Absolutely Horrible'), (1, 'Bad'), (2, 'Drinkable'), (3, 'Ok | Normal'), (4, 'Pretty Good'), (5, 'Good'), (6, 'Very Good'), (7, 'Excellent'), (8, 'Superb'), (9, 'Exceptional | Special'), (10, 'Unique | Rare | Exceptional | Special')], default='Ok | Normal', max_length=100)),
                ('posted_on', models.DateTimeField(auto_now=True)),
                ('drank_on', models.DateField()),
                ('was_special', models.BooleanField(default=False)),
                ('occasion', models.TextField(blank=True, default='no occasion', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('user_description', models.TextField(blank=True, default=None, null=True)),
                ('winery_description', models.TextField(blank=True, default='No Winery Description')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=4)),
                ('barcode', models.BigIntegerField(blank=True, default=None, null=True)),
                ('year', models.IntegerField()),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('wine_type', models.CharField(max_length=200)),
                ('create_on', models.DateTimeField(auto_now=True)),
                ('estimated_price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Winery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('user_description', models.TextField(blank=True, default=None, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('logo', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('tag_line', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('country', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='wine',
            name='made_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wines', to='wines.Winery'),
        ),
        migrations.AddField(
            model_name='note',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='wines.Wine'),
        ),
        migrations.AddField(
            model_name='note',
            name='by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
