# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-07 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='user_made_by',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='wine',
            name='made_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wines', to='wines.Winery'),
        ),
    ]
