# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-07 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0002_auto_20170707_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='country',
            field=models.CharField(default='cz', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wine',
            name='region',
            field=models.CharField(default='moravia', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wine',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
